language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - py.test --cov=pytsmp tests/
  - codecov --token=$CODECOV_TOKEN
